/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasipenghitunghari;

import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.Instant;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author irhas
 */
public class PenghitungHari extends javax.swing.JFrame {

    /**
     * Creates new form PenghitungHari
     */
    public PenghitungHari() {
        initComponents();
        LocalDate today = LocalDate.now();
        String todayStr = today.format(java.time.format.DateTimeFormatter.ofPattern("dd MMMM yyyy"));
        nowDate.setText("Tanggal hari ini: " + todayStr);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputBulan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        inputTahun = new javax.swing.JSpinner();
        countBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        hasilHari = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pilihTgl = new com.toedter.calendar.JCalendar();
        nowDate = new javax.swing.JLabel();
        resultDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Penghitung Hari");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("Penghitung Hari");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel9.setText("MUHAMMAD IRHASH FURQAN - 2410010596");

        inputBulan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANUARI", "FEBRUARI", "MARET", "APRIL", "MEI", "JUNI", "JULI", "AGUSTUS", "SEPTEMBER", "OKTOBER", "NOVEMBER", "DESEMBER" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bulan");

        inputTahun.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputTahun.setModel(new javax.swing.SpinnerNumberModel(2024, 1900, 2100, 1));
        inputTahun.setOpaque(false);

        countBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        countBtn.setText("HITUNG");
        countBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Tahun");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        hasilHari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hasilHari.setText("Masukkan Bulan dan Tahun");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Selisih Tanggal Dengan Sekarang");

        pilihTgl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pilihTglPropertyChange(evt);
            }
        });

        nowDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nowDate.setText("Tanggal Sekarang :");

        resultDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resultDate.setText("Pilih Tanggal Di atas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(inputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(countBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(inputBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jSeparator1))
                            .addComponent(hasilHari))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nowDate)
                            .addComponent(pilihTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(resultDate))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputBulan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasilHari)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pilihTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nowDate)
                        .addGap(32, 32, 32)
                        .addComponent(resultDate))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void countBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countBtnActionPerformed
        hitungJumlahHari();
    }//GEN-LAST:event_countBtnActionPerformed

    private void pilihTglPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pilihTglPropertyChange
        updateSelisihHari();
    }//GEN-LAST:event_pilihTglPropertyChange

    /**
     * @param args the command line arguments
     */
    
    private void hitungJumlahHari() {
        // Mendapatkan bulan dan tahun yang dipilih
        int bulan = inputBulan.getSelectedIndex() + 1; // index mulai dari 0
        int tahun = (int) inputTahun.getValue();

        // Buat LocalDate di hari pertama pada bulan dan tahun yang dipilih
        LocalDate tanggal = LocalDate.of(tahun, bulan, 1);

        // Menghitung jumlah hari dalam bulan yang dipilih
        int jumlahHari = tanggal.lengthOfMonth();

        // Memeriksa apakah tahun yang dipilih adalah tahun kabisat
        boolean isKabisat = tanggal.isLeapYear();

        // Menampilkan hasil pada label
        String hasil = "Jumlah hari: " + jumlahHari + " hari";
        hasil += isKabisat ? " (Tahun Kabisat)" : " (Bukan Tahun Kabisat)";
        hasilHari.setText(hasil);
    }
    
    private void updateSelisihHari() {
        // Mendapatkan tanggal yang dipilih dari JCalendar
        Date selectedDateUtil = pilihTgl.getDate(); 
        
        // Mengonversi Date menjadi string dalam format ISO_DATE ("yyyy-MM-dd")
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = formatter.format(selectedDateUtil);

        // Mengonversi string menjadi LocalDate
        LocalDate selectedDate = LocalDate.parse(dateString, DateTimeFormatter.ISO_DATE); // Mengonversi ke LocalDate

        // Mendapatkan tanggal hari ini
        LocalDate today = LocalDate.now();

        // Menghitung selisih periode antara tanggal yang dipilih dan tanggal hari ini
        Period period = Period.between(today, selectedDate);

        // Menghitung jumlah hari yang sudah lewat atau yang akan datang
        int years = period.getYears();
        int months = period.getMonths();
        int days = period.getDays();
        
        DateTimeFormatter customFormatter = DateTimeFormatter.ofPattern("d MMMM yyyy");
        String formattedDate = selectedDate.format(customFormatter);

        String result = "";

        if (period.isNegative()) {
            // Jika tanggal yang dipilih di masa lalu
            result = String.format("Tanggal %s adalah %d Tahun, %d Bulan, %d Hari, yang lalu",
                    formattedDate, -years,  -months, -days );
        } else {
            // Jika tanggal yang dipilih di masa depan
            result = String.format("Tanggal %s adalah %d Tahun, %d Bulan, %d Hari, yang akan datang",
                    formattedDate, -years,  -months, -days );
        }

        // Menampilkan hasil di label resultDate
        resultDate.setText(result);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenghitungHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenghitungHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton countBtn;
    private javax.swing.JLabel hasilHari;
    private javax.swing.JComboBox<String> inputBulan;
    private javax.swing.JSpinner inputTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel nowDate;
    private com.toedter.calendar.JCalendar pilihTgl;
    private javax.swing.JLabel resultDate;
    // End of variables declaration//GEN-END:variables
}
